#FROM ubuntu:16.04
FROM ubuntu:17.10

RUN apt update -y
RUN apt install -y python3
RUN apt install -y python3-pip
RUN apt install -y python3-matplotlib
RUN apt install -y texlive

RUN pip3 install --upgrade pip
RUN pip3 install docopt
RUN pip3 install pymongo
RUN pip3 install plotly
RUN pip3 install matplotlib

